### PR TITLE
:arrow_up: Adjust dependency specifiers

### LINKED ISSUE #4: Dependency updates
👋 I love this package! Thank you for creating it! Would you be open to me sending a pull request that updates some of the dependencies? I am having a dependency conflict with requests `2.28.1` and `^2.28.2`. I tested locally with removing the pinned dependencies in requirements.txt and setup.cfg and everything seems to work. Thanks again!

### PR DESCRIPTION
**Pull request by vdavez**
Changes requirements.txt and setup.cfg to have >= dependencies. Would close #4.

### CODE REVIEW

**Comment by dherincx92** [comment]
I have to do this better, but if you want to just bump up the version on the setup.cfg to 1.1.0 that would be great.

**Comment by dherincx92** [comment]
Just make sure to pull...I made some changes so to prevent conflict, just pull the latest and just update that version

**Comment by vdavez** [comment]
Alright. Rebased and updated the version to `1.1.0`. Let me know if you need me to do anything else.

**Comment by dherincx92** [comment]
Closing PR since I merged in this work with my minor branch fixing the duplicate tag name logic

**Pull request closed without merging**
